### NumPy arrays

In [39]:
import numpy as np
from numpy.random import randint

In [4]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2) # número inicial, número final (não incluso), steps

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5,5) # normal distribution 0 to 1

array([[0.3098407 , 0.09936683, 0.00807738, 0.52424913, 0.47367272],
       [0.04597264, 0.39415949, 0.63199029, 0.95809712, 0.30365938],
       [0.22698596, 0.79848349, 0.40200385, 0.11521613, 0.77773002],
       [0.34984221, 0.17474076, 0.70118904, 0.50562054, 0.07949967],
       [0.42829901, 0.39192703, 0.0415709 , 0.27387916, 0.94740604]])

In [20]:
np.random.randn(4,4)

array([[-0.71815912, -0.84704144,  0.13310791, -0.58548361],
       [-0.21873442, -1.77203255,  1.14729284,  0.45523946],
       [-0.43105152, -1.58974707, -1.49251916,  0.50374668],
       [-0.13188231,  1.05980315, -0.32475902,  0.10259639]])

In [22]:
np.random.randint(1,100,10)

array([38, 31, 12, 23, 11, 30, 33, 97, 53, 81])

In [23]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)
ranarr

array([28,  1, 15, 36, 37, 14, 49,  5,  4,  5])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

49

In [31]:
ranarr.min()

1

In [32]:
ranarr.argmax()

6

In [33]:
ranarr.argmin()

1

In [37]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int32')

In [40]:
randint(2,10)

3